### ISSUE TITLE
Hot Reload works but state is lost

### ISSUE THREAD

**Issue by empz** [mobxjs/react-mobx-boilerplate#4]
I've added some substores to the main AppStore. Some of them holds some arrays of stuff that get's added and displayed. These arrays are all initialized as empty in its store constructor.

Whenever I make a change in a component, HMR works and hot reloads, but my state is lost (arrays are empty).
In this boilerplate, the timer is not lost when hot reloading. 

I haven't changed anything in the files `App.ts`, `index.ts` and `root.tsx`.

Any ideas why I'm losing my state?

Thanks

**Comment by srolel** [comment]
Look at `AppState#reload`. When HMR happens, a new `App` is instantiated (in `index.ts#45`) using the previous `appState`, and the `App` constructor creates a new `AppState` instance and reloads the previous instance's state into the new instance.

`AppState#reload`, by default, is implemented as:

```
reload(store: AppStateProps) {
  Object.assign(this, store);
  return this;
}
```

So you may need to customize it, depending on how the substores are implemented. I just tried the simplest case and it does seem to work:

```
class SubStore {
  @observable arr = [];
}

class AppState implements AppStateProps {
/* ... */
  @observable subStore = new SubStore();
/* ... */
  @action incrementTimer = () => {
    this.timer += 1;
    this.subStore.arr.push(this.timer);
  }
/* ... */
}
```

And when I log the array, I do get the whole array through hot reloading.

**Comment by empz** [comment]
Thanks for the quick response!

I've found the problem:
I was resetting the array in `AppState.unload()` method because it made sense in my head. But I do see now that method is called when hot reloading with `newProps`.  Inspecting `newProps` shows the store with the arrays filled as it should be, but after `unload()` they are not being repopulated.
I still don't fully understand how this works but I guess I'll just leave the unload method empty.


![image](https://cloud.githubusercontent.com/assets/412489/26139311/079578ee-3aa6-11e7-8877-aa4259ea27f9.png)

**Comment by srolel** [comment]
Note the order. The `App` instance is created first, then `props.app.unload()`. So the array was filled first, then calling `unload` emptied it and that's the new state for the app. I'll make a few changes to make sure it's clearer.

**Comment by sudosean** [comment]
Hi, I am running into the same issue. How would I implement this for a basic app setup like so: 
```
import React from "react";
import ReactDOM from "react-dom";

import App from "./common/App";

//Needed for React Developer Tools
window.React = React;
if(__DEV__ && module.hot){
  console.log(true);
}
ReactDOM.render(<App />, document.getElementById("root"));
```

**Comment by sudosean** [comment]
not using ts btw
