### ISSUE TITLE
Code Inquiry

### ISSUE THREAD

**Issue by wildeyes** [mobxjs/react-mobx-boilerplate#7]
What's the rationale behind [currStore = Object.assign(prevStore)](https://github.com/mobxjs/react-mobx-boilerplate/blob/b6bf5bd/src/stores/AppState.ts#L37)? that could lead to unfresh state..?

**Comment by srolel** [comment]
Facilitates hot reloading of the store.

**Comment by benjamingr** [comment]
It's in the `reload` method - you can't just swap the object (mobx works with getters/setters) and you need to do hot reload so you need the old app state somehow.
